apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Real User Monitoring
  description: Real User Monitoring Service
  tags:
    - node
    - frontend
  links:
    - url: https://opsverse-demo-us.us-east4.gcp.opsverse.cloud/?orgId=1&var-Cluster=opsverse-demo&var-namespace=opsverse-demo
      title: Observe
      icon: dashboard
  annotations:
    circleci.com/project-slug: github/OpsVerseIO/real-user-monitoring
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: real-user-monitoring
    prometheus.io/rule: container_memory_usage_bytes{pod=~"rum-.*"},sum by (container) (rate(container_cpu_usage_seconds_total{pod=~"adservice-.*"}[5m]))
spec:
  type: service
  lifecycle: production
  owner: AdService-team
  system: online-store
